apiVersion: apps/v1
kind: Deployment
metadata:
  name: webcard
spec:
  minReadySeconds: 3
  revisionHistoryLimit: 
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: webcard
  template:
    metadata:
      labels:
        app: webcard
    spec:
      containers:
      - name: webcard-pod
        image: kashapovd/webcard:latest
        imagePullSecrets:
        - name: dockerhub
        resources:
          limits:
            cpu: 2000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 64Mi